# Generated by Django 2.1.7 on 2019-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Cover', 'Cover'), ('Scan', 'Scan'), ('Other', 'Other')], max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('meme_img', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
    ]
