# Generated by Django 2.1.7 on 2019-07-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_auto_20190707_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
